name: flutter_fx
description: "A set of state & navigation manager for flutter. It allows you to update wisely your states and to navigate easily."
version: 0.0.15+1
homepage: https://crianpiro.de/
repository: https://github.com/crianpiro/flutter_fx
issue_tracker: https://github.com/crianpiro/flutter_fx/issues
funding:
  - https://buymeacoffee.com/crianpiro
topics:
  - state
  - navigation
  - state-manager
  - navigation-manager
  - state-management

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0