name: flutter_fx
description: "State & navigation manager for flutter. It allows you to update wisely your states and to navigate easily."
version: 0.0.2
homepage: https://crianpiro.de/

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0